# Generated by Django 3.2.13 on 2022-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20220705_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='web_address',
            field=models.URLField(default='www.sample.com'),
        ),
    ]
