# Generated by Django 3.2.13 on 2022-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_web_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='slug',
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
