# Generated by Django 3.2.13 on 2022-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20220719_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='activity_website',
            field=models.URLField(blank=True),
        ),
    ]
