# Generated by Django 3.2.13 on 2022-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_alter_idea_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='picture',
            field=models.ImageField(default='placeholder', upload_to='media/'),
        ),
    ]
